title: SiHui Yan's Homepage
page-top-title: SiHui Yan
top-section-bg-text: Computer Science
home-subtitle: SiHui Yan&ensp;|&ensp;闫思慧
copyright-text: '&copy; SiHui Yan 2023-2024. All Rights Reserved.'

baseurl: "https://yansihui999.github.io"  # 项目名称（如 https://username.github.io/project-name）
url: "https://yansihui999.github.io"  # 个人网址
