title: Sen Li's Homepage
page-top-title: Sen Li
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'

baseurl: "https://yansihui999.github.io"  # 项目名称（如 https://username.github.io/project-name）
url: "https://yansihui999.github.io"  # 个人网址
